config/routes.rb
Rails.application.routes.draw do
  root 'shops#index'
  #root 'products#index'
  devise_for :users, controller: {
    registrations: 'registrations'
  }
  resources :products
  resources :shops, only:[:index, :show]
  resources :order_items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order_list
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    unit_price*quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_subtotal
    self[:total] = total * quantity
  end

end

app/models/order_list.rb
class OrderList < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def show
    @order_items = current_order.order_items
  end

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/product.rb
class Product < ApplicationRecord
validates :name, :price, :category, :size, presence: true
has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @order_item = @order.order_items.new(order_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_params)
    @order_items = current_order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = current_order.order_items
  end

private

  def order_params
    params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact; end

  def about; end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @products = Product.all
    @order_items = current_order.order_items.new
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render 'products/show'
    end
  end

  def edit; end

  def update
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :size, :category, :price)
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @products = Product.all

    #@order_items = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # def current_order
  #   if session[:order_id].nil?
  #     OrderList.new
  #   else
  #     OrderList.find(session[:order_id])
  #   end
  # end

  def current_order
    @current_order ||= OrderList.find_by_id(session[:order_id]).presence || OrderList.new
  end

end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="myfooter" style="padding:100px; background: ghostwhite; font-size:16px; display:relative; left:600px; font-size:16px; color:gray; box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);">
    <div class="myfooter-links" style="font-size:16px; color:gray; margin-left:650px;">
      <a class="symbol link" href="#"><i class="fab fa-github" style=" left:600px; font-size:16px; color:gray; text-align:center; justify-content:center;"></i></a>
      <a class="symbol link" href="#"><i class="fab fa-instagram" style=" left:600px; font-size:16px; color:gray;"></i></a>
      <a class="symbol link" href="#"><i class="fab fa-facebook" style=" left:600px; font-size:16px; color:gray;"></i></a>
      <a href="#"><i class="fab fa-twitter" style=" left:600px; font-size:16px; color:gray;"></i></a>
      <a href="#"><i class="fab fa-linkedin" style=" left:600px; font-size:16px; color:gray;"></i></a>
    </div>
    <div style="margin-left:650px;">
      made with <i class="fas fa-heart" style="display:absolute; left:200px; font-size:16px;"></i> by Roxy. <br>
      Any illegal reproduction of this content will result in immediate legal action <i class="fad fa-tombstone"> </i>
    </div>
  </div>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tribe 🌊 Alive </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" type="image/png" href="/images/wolf.png">
    <link href="https://fonts.googleapis.com/css2?family=Bungee&display=swap" rel="stylesheet">
    <script src="jquery-1.6.1.js"></script>
    <script src="my_jquery.js"></script>
    <script src="index.js"> </script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <% if user_signed_in? %>
    <div class = "navbar-item has-dropwdown is-hoverable">
      <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
      <div class="navbar-dropdown is-right">
      <%= link_to 'Edit Profile', edit_user_registration_path, class:"btn btn-success"  %>
      <%= button_to 'Log out', destroy_user_session_path, method: :delete, class:"btn btn-dark", style:'margin-top:7px;' %>


      </div>
    </div>
 <!-- The Index div will be put here -->
    <% else %>
    <div class="logdetails">
    <ul class= "navbar-side">
       <li class= "navbar-itembutton"><%= link_to "Sign In", new_user_session_path %></li>
       <li class= "navbar-itembutton" ><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
    </ul>
    </div>
  </head>


  <body>
  <%= yield %>

  <footer>
    <%= render 'layouts/footer' %>
  </footer>

  </body>

</html>

app/views/pages/about.html.erb
<h1 class="itz a me"> This is Roxy! </h1>
<p class="itz a me" > I am a designer and a natural sports enthusiast. </p>

<h2 class="itz a me" >Inspired by nature, I love showcasing my interests in my artistic work.</h2>
 <%= link_to "Back to home page", products_path %>

app/views/pages/contact.html.erb
<h1> My phone number </h1>
<h2> My etsy account </h2>
<h3> My instagram </h3>
<h4> My email </h4>
 <%= link_to "Back to home page", products_path %>

app/views/products/_form.html.erb
<%= simple_form_for(@product), remote: true do |f|  %>
<%= f.input :name %>
<%= f.input :category %>
<%= f.input :size %>
<%= f.input :price %>
<%= f.submit %>
<% end %>

app/views/products/_forrm.html.erb
<%= simple_form_for(product) do |f|  %>
<%= f.input :name %>
<%= f.input :category %>
<%= f.input :rating %>
<%= f.input :price %>
<%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<%= simple_form_for(@product), remote: true do |f|  %>
<%= f.input :name %>
<%= f.input :category %>
<%= f.input :size %>
<%= f.input :price %>
<%= f.submit %>
<% end %>


<!--

<div class="formstyle", product: @product>
<%= render "form" %>
</div>



-->

app/views/products/index.html.erb
<div class="trypad">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1623038455007-891466ff6016?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1286)">
    Tribe Alive
  </div>
  <div class="navbar-itemb">
    <ul>
      <li> <%= link_to "Products", products_path, class:"greennav" %> </li>
      <li> <%= link_to "About Us", about_path, class:"greennav"%></li>
      <li> <%= link_to "Contact", contact_path, class:"greennav"%></li>
    </ul>
  </div>
</div>

<!-- >
<div class="container">
  <h1>Welcome to the tribe. Here's a list of our products:</h1>
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-md-4 col-sm-6 mt-3" style="max-width: 1450px;">
            <div class="drone-cards mx-3 h-100">
              <img class="pics" src="https://images.asos-media.com/products/asos-design-oversized-t-shirt-in-orange-with-graphic-back-print/201847608-1-apricotcream?$n_640w$&wid=634&fit=constrain" >
                  <div class="drone-cards-info" stlye="display:relative;">
                          <%= link_to product.name, product_path(product), class:"text-decoration-none" %>
                          <p> Price (€): <%= product.price %></p>
                          <p class="p-index" style="display:absolute; top:20px;"> Category: <%= product.category %></p>
                        <% end %>
                    <div>
                </div>
          <div>
    </div>
</div>
-->
<div class="container">

  <div class="row mt-1" style="margin-top: 15.25rem !important;" >
  <h1 class="welcome h1"> OUR PRODUCTS </h1>

    <form name="search-products" >
      <input type="text" id="search" placeholder="Search" aria-label="Search" style="padding:4px 0px;">
      <button class="btn btn-secondary" type="Submit" style="padding: 8px 10px; border-radius:15px; justify-content:flex-start;"> Search </button>
    </form>

    <li class="js" style="list-style:none;"><% @products.each do |product| %> </li>
      <div class="col-md-4 col-sm-6 col-lg-4 mt-9 p-5" style="max-width: 1450px; border-radius:50px;">
        <div class="drone-cards mx-3 h-100">
          <img src="https://images.unsplash.com/photo-1601610694692-5575b3904552?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1288">
          <div class="drone-cards-info" style="display:relative;">
            <%= link_to product.name, product_path(product), class:"text-decoration-none" %>
            <p> Price (€): <%= product.price %></p>
            <p class="p-index" style="display:absolute; top:20px;"> Category: <%= product.category %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<%= simple_form_for(@product), remote: true do |f|  %>
<%= f.input :name %>
<%= f.input :category %>
<%= f.input :size %>
<%= f.input :price %>
<%= f.submit %>
<% end %>


<!-- <div class="formstyle">
<%= render "form" %>
</div>
-->

app/views/products/show.html.erb
<h1 class="show h1"><%= @product.name %> $<%= @product.price %></h1>
<h2 class="show h2"><%= @product.size %></h2>
<%= link_to 'back', products_path %>
<%= link_to 'edit', edit_product_path(@product) %>
<%= link_to 'delete', product_path(@product), method: :delete, data: {confirm: 'are you sure?'} %> <!-- By default, link to is a get request, hence you need to specify, method: delete>

app/views/shops/index.html.erb
<div class="trypad">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1623038455007-891466ff6016?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1286)">
    Tribe Alive
  </div>
  <div class="navbar-itemb">
    <ul>
      <li> <%= link_to "Products", products_path, class:"greennav" %> </li>
      <li> <%= link_to "About Us", about_path, class:"greennav"%></li>
      <li> <%= link_to "Contact", contact_path, class:"greennav"%></li>
    </ul>
  </div>
</div>

<!-- >
<div class="container">
  <h1>Welcome to the tribe. Here's a list of our products:</h1>
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-md-4 col-sm-6 mt-3" style="max-width: 1450px;">
            <div class="drone-cards mx-3 h-100">
              <img class="pics" src="https://images.asos-media.com/products/asos-design-oversized-t-shirt-in-orange-with-graphic-back-print/201847608-1-apricotcream?$n_640w$&wid=634&fit=constrain" >
                  <div class="drone-cards-info" stlye="display:relative;">
                          <%= link_to product.name, product_path(product), class:"text-decoration-none" %>
                          <p> Price (€): <%= product.price %></p>
                          <p class="p-index" style="display:absolute; top:20px;"> Category: <%= product.category %></p>
                        <% end %>
                    <div>
                </div>
          <div>
    </div>
</div>
-->
<div class="container">

  <div class="row mt-1" style="margin-top: 15.25rem !important;" >
  <h1 class="welcome h1"> OUR PRODUCTS </h1>

    <form name="search-products" >
      <input type="text" id="search" placeholder="Search" aria-label="Search" style="padding:4px 0px;">
      <button class="btn btn-secondary" type="Submit" style="padding: 8px 10px; border-radius:15px; justify-content:flex-start;"> Search </button>
    </form>

      <td>
      <% form_with model: @order_items, local: false do |f| %>
      <%= f.hidden_field :product_id, :value => product.id %>
      <%= f.number_field :quantity, :value => 1, :min => 1 %>
      <%= f.submit "Add to Card" %>
      <% end %>
     </td>
    <li class="js" style="list-style:none;"><% @products.each do |product| %> </li>
      <div class="col-md-4 col-sm-6 col-lg-4 mt-9 p-5" style="max-width: 1450px; border-radius:50px;">
        <div class="drone-cards mx-3 h-100">
          <img src="https://images.unsplash.com/photo-1601610694692-5575b3904552?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1288">
          <div class="drone-cards-info" style="display:relative;">
            <%= link_to product.name, shop_path(product), class:"text-decoration-none" %>
            <p> Price (€): <%= product.price %></p>
            <p class="p-index" style="display:absolute; top:20px;"> Category: <%= product.category %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/show.html.erb
<h1 class="show h1"><%= @product.name %> $<%= @product.price %></h1>
<h2 class="show h2"><%= @product.size %></h2>
<%= link_to 'back', root_path %>